### ISSUE TITLE
Syntax Error when I run it

### ISSUE THREAD

**Issue by aharris88** [sindresorhus/get-port-cli#1]
/usr/local/lib/node_modules/get-port-cli/cli.js:3
    const meow = require('meow');
    ^^^^^
    SyntaxError: Use of const in strict mode.
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/get-port-cli/blob/95d8bb2d91bf728eb5065951e5170eae13539328/package.json#L16
